name: test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  intl_utils: ^2.4.0
  location: ^7.0.1
  flag: ^7.0.0
  image_picker: 0.8.7+3
  cached_network_image: ^3.2.3 # For efficient image caching
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  flutter_bloc: ^8.0.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  http_parser: ^4.0.0
  image: ^4.5.2
  #google_maps_flutter: ^2.0.9
  #google_maps_flutter: ^2.10.0
   # Add Google Maps Flutter package
  #image_picker: ^0.8.5+3  # Uncommented the image_picker version you want to use

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - images/
    - lib/l10n/  # For localization files

  generate: true  # Enable code generation (for localization files)
